<?php
/**
 * Do not edit this file.
 * It just  include artvens-theme-loader
*/

define( 'ARTVENS_THEME_PATH', dirname( __FILE__ ) . '/includes' );

include_once ARTVENS_THEME_PATH.'/theme-core/artvens-theme-loader.php';